### ISSUE TITLE
arg min or max for eq (6)

### ISSUE THREAD

**Issue by ofTarradiddle** [younader/dnnr#41]
Why is arg min W for equation 6 if we expect there to be higher correlations between distance and error in the paper? Should this be arg max instead?

**Comment by ofTarradiddle** [comment]
@younader, any thoughts on this? Especially since it appears in the scaling python model the arg max of the cosine similarity is taken, as opposed to the arg min of the corr in the paper.

**Comment by younader** [comment]
Hello @ofTarradiddle, thanks for pointing out the typo! Yeah the paper is missing the negative sign on the arg min. will update the arxiv version soon. And apologies for the delayed reply.
